# Generated by Django 5.2 on 2025-05-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField()),
                ('contact', models.PositiveIntegerField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('issue_type', models.CharField(choices=[('', ''), ('', ''), ('', '')])),
                ('description', models.TextField(blank=True)),
                ('issue_img', models.ImageField(blank=True, null=True, upload_to='issue_pics/')),
            ],
        ),
    ]
