# Generated by Django 5.2 on 2025-05-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('contact', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('availability', models.DateField(blank=True)),
                ('work_area', models.CharField(choices=[('Field Work', 'Field Work'), ('Awareness Programs', 'Awareness Programs'), ('Tech Support', 'Tech Support')])),
            ],
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='issue',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('Dried Well', 'Dried Well'), ('Leakage', 'Leakage'), ('Waterlogging', 'Waterlogging')]),
        ),
    ]
